# Load data

In [1]:
%matplotlib inline
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from os import listdir
from os.path import isfile, join
import numpy
from skimage import io

In [4]:
from skimage.io import imread_collection
dirName = r"/dtu/datasets1/02514/hotdog_nothotdog/train/hotdog/*.jpg"
train_hotdog = imread_collection(dirName)

In [5]:
print(train_hotdog[0])

[[[253 254 255]
  [253 254 255]
  [255 254 252]
  ...
  [254 254 254]
  [253 253 253]
  [253 253 253]]

 [[253 254 255]
  [254 254 255]
  [255 254 252]
  ...
  [254 254 254]
  [253 253 253]
  [253 253 253]]

 [[254 254 255]
  [254 254 255]
  [255 254 252]
  ...
  [254 254 254]
  [253 253 253]
  [253 253 253]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [253 255 254]
  [253 255 254]
  [253 254 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [253 255 254]
  [253 255 254]
  [253 254 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [252 253 255]
  [252 253 255]
  [252 253 255]]]


In [3]:
image_filepath = r"/dtu/datasets1/02514/hotdog_nothotdog/train/hotdog/hotdog (9).jpg"
io.imread(image_filepath)

array([[[ 87,  80,  74],
        [ 86,  77,  72],
        [ 84,  73,  71],
        ...,
        [204, 202, 226],
        [205, 203, 227],
        [205, 203, 227]],

       [[ 87,  71,  71],
        [ 83,  67,  67],
        [ 80,  62,  62],
        ...,
        [205, 203, 227],
        [206, 204, 228],
        [206, 204, 228]],

       [[ 81,  50,  56],
        [ 77,  46,  51],
        [ 71,  40,  45],
        ...,
        [205, 203, 227],
        [207, 205, 229],
        [208, 206, 230]],

       ...,

       [[ 13,  75, 210],
        [ 25,  84, 222],
        [ 40,  96, 243],
        ...,
        [ 85, 108, 150],
        [ 90, 113, 155],
        [ 94, 117, 159]],

       [[ 24,  88, 222],
        [ 33,  96, 235],
        [ 43, 101, 247],
        ...,
        [ 79, 107, 147],
        [ 84, 112, 152],
        [ 86, 114, 154]],

       [[ 13,  87, 218],
        [ 34, 106, 242],
        [ 16,  83, 226],
        ...,
        [ 72, 104, 143],
        [ 77, 109, 148],
        [ 83, 115, 154]]